In [2]:
import numpy as np
from time import process_time

In [3]:
a = [i for i in range(10000000)]
start_time = process_time()
b = [i+4 for i in a]
end_time = process_time()

print( end_time - start_time)

0.421875


In [4]:
np_array = np.array([i for i in range(10000000)])

st = process_time()
np_array += 4
end = process_time()
print(end-st)

0.0


***Numpy*** 


In [11]:
list = [1,3,4,5]
print(type(list),"\n")

np_array = np.array(list)
print(type(np_array))


<class 'list'> 

<class 'numpy.ndarray'>


***Dimension of array***

In [22]:
d1_arr = np.array(1)
print(np.ndim(d1_arr))
d1_arr.shape

0


()

In [19]:
d2_arr = np.array([11,23])
print(np.ndim(d2_arr))
d2_arr.shape

1


(2,)

In [25]:
d3_arr = np.array([[1,2,3],[1,3,4]]) #inner elements should be in same length
print(np.ndim(d3_arr))
d3_arr.shape

2


(2, 3)

In [26]:
d4_arr = np.array([[[1,3,4],[1,3,4]],[[2,3,5],[4,3,5]]])
print(np.ndim(d4_arr))
d4_arr.shape

3


(2, 2, 3)

In [33]:
#reshape the array
list = np.array([i for i in range(10)],dtype=float) #dtype helps to mention data type
print(list)
print("dimension : ",np.ndim(list))
list_2d = list.reshape(2,-1)
print(list_2d)
print("dimension : ",np.ndim(list_2d))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
dimension :  1
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
dimension :  2


***Initial Placeholders***

In [35]:
x = np.ones((4,2),dtype=int) #all element as 1
print(x)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [38]:
x = np.zeros((3,3),dtype=int) #all element as 0
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
x = np.full((5,6),19,dtype=int) #all element as specific value
print(x)

[[19 19 19 19 19 19]
 [19 19 19 19 19 19]
 [19 19 19 19 19 19]
 [19 19 19 19 19 19]
 [19 19 19 19 19 19]]


In [43]:
x = np.eye(6,dtype=int) #creating identy matrix where 6 is number of columns and rows
print(x)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


***Creation with random values***

In [44]:
x = np.random.random((2,4)) # creation with random values with shape 2,4
print(x)

[[0.76706698 0.78548608 0.74525449 0.76649909]
 [0.41041717 0.81912679 0.32101261 0.29384415]]


In [45]:
#creation with random values b/w the range 100 to 120 with shape 3,3
x = np.random.randint(100,120,(3,3)) 
print(x)

[[109 110 112]
 [116 104 100]
 [119 106 111]]


In [53]:
#creation with evenly spaced elements
x = np.linspace(10,40,6,dtype=int) # 10 ,40 is range & 6 is no. of elem
print(x)

[10 16 22 28 34 40]


In [58]:
#creation with evenly spaces with steps 
x = np.arange(10,30,2)
y = np.arange(10,30,5)
print("Steps with 2 : ",x)
print("Steps with 5 : ",y)

Steps with 2 :  [10 12 14 16 18 20 22 24 26 28]
Steps with 5 :  [10 15 20 25]


*** Conversion of list & tuple to ndarray ***

In [60]:
l = [1,3,5,6]
print("Normal List : ",type(l))


nd_arr = np.asarray(l) #converting list to nd array
print("ndarray : ",type(nd_arr))

Normal List :  <class 'list'>
ndarray :  <class 'numpy.ndarray'>


In [62]:
l = (1,3,5,6)
print("Normal Tuple : ",type(l))


nd_arr = np.asarray(l) #converting tuple to nd array
print("ndarray : ",type(nd_arr))

Normal Tuple :  <class 'tuple'>
ndarray :  <class 'numpy.ndarray'>


***Analysis a np array***

In [71]:
c = np.random.randint(10,100,(3,3))
print(c)

[[87 65 86]
 [18 34 87]
 [24 40 48]]


In [72]:
#shape of the array 
print(c.shape)

(3, 3)


In [73]:
#no. of dimention that array have
print(np.ndim(c))
#     OR
print(c.ndim)

2
2


In [74]:
# counting of no. of elements in an array
print(c.size)

9


In [75]:
 #finding the data type
print(c.dtype)

int32


***Mathematical Operations***

In [77]:
#contcatenation will happen will add two normal list
l1 = [1,3,4]
l2 = [1,2,4]
print(l1 + l2)

[1, 3, 4, 1, 2, 4]


In [78]:
# for Np array it will sum 2 list by using + operator
l1 = np.array([1,3,4])
l2 = np.array([1,2,4])
print(l1 + l2)

[2 5 8]


In [81]:
#all other math operations
print(l1 + l2)
print(l1 - l2)
print(l1 * l2)
print(l1 / l2)

[2 5 8]
[0 1 0]
[ 1  6 16]
[1.  1.5 1. ]


In [83]:
# using functions
print(np.add(l1,l2))
print(np.subtract(l1,l2))
print(np.multiply(l1,l2))
print(np.divide(l1,l2))

[2 5 8]
[0 1 0]
[ 1  6 16]
[1.  1.5 1. ]


***array manipulation***

In [84]:
a = np.random.randint(10,100,(2,4))
print(a)
a.shape

[[63 46 21 23]
 [64 88 44 99]]


(2, 4)

In [85]:
#tranpose of array 
trans = np.transpose(a)
print(trans)
trans.shape

[[63 64]
 [46 88]
 [21 44]
 [23 99]]


(4, 2)

In [91]:
a = np.random.randint(2,10,(2,4))
print(a)
print(a.shape)
trans = a.T
print("Transpose : \n",trans)
print(trans.shape)

[[4 7 8 7]
 [7 4 2 9]]
(2, 4)
Transpose : 
 [[4 7]
 [7 4]
 [8 2]
 [7 9]]
(4, 2)
